version: "3.8"

services:
  db:
    image: mariadb:latest
    restart: always
    container_name: maraidb
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: gacha_game
      MYSQL_USER: gacha_user
      MYSQL_PASSWORD: gachapass
    
    ports:
      - "3308:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  api:
    build: .
    container_name: gacha_api
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env
    command: sh -c "npx prisma migrate deploy && npm run dev"

volumes:
  mariadb_data: